//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeStayVNEntities : DbContext
    {
        public HomeStayVNEntities()
            : base("name=HomeStayVNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<About_Us_Admin> About_Us_Admins { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Adress> Adresses { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<HomeStay> HomeStays { get; set; }
        public virtual DbSet<ImageHomeStay> ImageHomeStays { get; set; }
    }
}
